# Testing MePn models

In [1]:
import os
import cobra
from modelseedpy import MSBuilder, MSATPCorrection, MSMedia, MSGapfill
import json
from tqdm import tqdm
import cobrakbase

modelseedpy 0.4.2
cobrakbase 0.4.0

In [2]:
config = cobra.Configuration()
config

solver: cplex
tolerance: 1e-07
lower_bound: -1000.0
upper_bound: 1000.0
processes: 335
cache_directory: /home/fliu/.cache/cobrapy
max_cache_size: 104857600
cache_expiration: None

In [3]:
mepe = {
    'Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.20.contigs',
 'Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.32.contigs',
 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs',
 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.27.contigs',
 'Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.28.contigs',
 'Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.7.contigs',
 'Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.31.contigs',
 'Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs',
 'Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.35.contigs',
 'Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.49.contigs',
 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.contigs',
 'Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs',
 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.143.contigs',
 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.32.contigs',
 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs',
 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.16.contigs',
 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs',
 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs',
 'Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.55.contigs',
 'Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.88.contigs',
 'Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.95.contigs',
 'Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.17.contigs',
 'Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.18.contigs',
 'Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.45.contigs',
 'Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.47.contigs',
 'Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.17.contigs',
 'Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.8.contigs'}

In [4]:
models = {}
for i in tqdm(mepe):
    filename_model = f'./genome_scale/{i}.json'
    if os.path.exists(filename_model):
        models[i] = cobra.io.load_json_model(filename_model)
    else:
        print(f'skip {i}')

 26%|██▌       | 7/27 [00:03<00:11,  1.78it/s]

skip Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.16.contigs

 48%|████▊     | 13/27 [00:06<00:07,  1.96it/s]

skip Salt_Pond_MetaG_R2_A_D2_MG_DASTool_bins_metabat.14.contigs

 63%|██████▎   | 17/27 [00:08<00:04,  2.23it/s]

skip Salt_Pond_MetaG_R1_C_D1_MG_DASTool_bins_metabat.31.contigs

100%|██████████| 27/27 [00:13<00:00,  1.98it/s]

In [25]:
model1.summary()

In [ ]:
for r in model1.reactions:
    r2 = model2.reactions.get_by_id(r.id)
    if r.lower_bound != r2.lower_bound or r.upper_bound != r2.upper_bound:
        print(r.id, r.build_reaction_string(True))
        print(r.lower_bound, r.upper_bound, r2.lower_bound, r2.upper_bound)

In [29]:
for r in model1.reactions:
    r2 = model2.reactions.get_by_id(r.id)
    if r.lower_bound != r2.lower_bound or r.upper_bound != r2.upper_bound:
        print(r.id, r.build_reaction_string(True))
        print(r.lower_bound, r.upper_bound, r2.lower_bound, r2.upper_bound)

EX_cpd10515_e0 Fe2+ [e0] -->
-0.0 1000.0 -1000.0 1000.0
EX_cpd00159_e0 L-Lactate [e0] <=>
-10.0 1000.0 -1.0 1000.0

In [23]:
model1 = models['Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.27.contigs']

In [24]:
model2.summary()

In [22]:
model2 = cobra.io.load_json_model(f'./genome_scale/Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.27.contigs.json')

In [17]:
res = {}
res_phosphate = {}
for model_id, model in tqdm(models.items()):
    model.reactions.EX_cpd00009_e0.lower_bound = 0.00
    sol = cobra.flux_analysis.pfba(model)
    res[model_id] = sol
    model.reactions.EX_cpd00009_e0.lower_bound = 0.01
    res_phosphate[model_id] = None
    try:
        res_phosphate[model_id] = cobra.flux_analysis.pfba(model)
    except Exception as ex:
        pass
    model.reactions.EX_cpd00009_e0.lower_bound = 0.00

100%|██████████| 24/24 [00:20<00:00,  1.17it/s]

In [16]:
for model_id, model in models.items():
    sol_pi = res_phosphate[model_id]
    sol_pi_flux_bio1 = sol_pi.fluxes['bio1'] if sol_pi else 0
    print("{0}\t{1:.4f} {2:.4f}".format(model_id, res[model_id].fluxes['bio1'], sol_pi_flux_bio1))

Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.8.contigs	0.0465 0.0464
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.17.contigs	0.0514 0.0514
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.95.contigs	0.0401 0.0383
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs	0.0502 0.0502
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.55.contigs	0.0470 0.0469
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.45.contigs	0.0467 0.0466
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.28.contigs	0.0502 0.0000
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.18.contigs	0.0452 0.0000
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.17.contigs	0.0401 0.0382
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.32.contigs	0.0452 0.0435
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.7.contigs	0.0455 0.0000
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.32.contigs	0.0469 0.0000
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs	0.0400 0.0000
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs	0.0508 0.0507
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs	0.0509 0.0000
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.88.contigs	0.0311 0.0000
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.49.contigs	0.0511 0.0511
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.20.contigs	0.0513 0.0000
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.27.contigs	0.0497 0.0000
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs	0.0497 0.0497
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.35.contigs	0.0453 0.0435
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.16.contigs	0.0486 0.0485
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.143.contigs	0.0510 0.0510
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.47.contigs	0.0498 0.0498

Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.8.contigs	0.4654 0.4653
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.17.contigs	0.5141 0.5140
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs	0.5086 0.0000
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.47.contigs	0.4983 0.4983
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs	0.5077 0.5076
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.88.contigs	0.0000 0.0000
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.45.contigs	0.4670 0.4669
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.17.contigs	0.0000 0.0000
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.49.contigs	0.5111 0.5111
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.16.contigs	0.4858 0.4858
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.95.contigs	0.0000 0.0000
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.20.contigs	0.5129 0.0000
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs	0.4969 0.4969
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs	0.3998 0.0000
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs	0.5021 0.5020
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.27.contigs	0.0000 0.0000
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.32.contigs	0.4524 0.4506
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.55.contigs	0.4698 0.4698
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.18.contigs	0.4525 0.0000
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.35.contigs	0.4527 0.4509
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.32.contigs	0.4688 0.0000
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.28.contigs	0.5020 0.0000
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.7.contigs	0.4547 0.0000
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.143.contigs	0.5102 0.5102

In [8]:
for model_id, model in models.items():
    print(model_id, len(model.reactions))

Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.47.contigs 1223
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.28.contigs 1277
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.18.contigs 1251
Salt_Pond_MetaG_R2_C_D2_MG_DASTool_bins_concoct_out.45.contigs 1263
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.95.contigs 1068
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.32.contigs 1255
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_metabat.27.contigs 1099
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.38.contigs 1227
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.143.contigs 1276
Salt_Pond_MetaG_R1_B_D2_MG_DASTool_bins_concoct_out.51.contigs 1154
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_metabat.17.contigs 1312
Salt_Pond_MetaG_R1_B_H2O_MG_DASTool_bins_metabat.7.contigs 1177
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_concoct_out.17.contigs 1071
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.49.contigs 1247
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.19.contigs 1284
Salt_Pond_MetaG_R2_A_D1_MG_DASTool_bins_concoct_out.35.contigs 1210
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.55.contigs 1253
Salt_Pond_MetaG_R2_restored_C_black_MG_DASTool_bins_metabat.8.contigs 1226
Salt_Pond_MetaG_R1_B_D1_MG_DASTool_bins_metabat.20.contigs 1283
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.10.contigs 1335
Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.88.contigs 939
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_metabat.16.contigs 1275
Salt_Pond_MetaG_R2_B_D2_MG_DASTool_bins_concoct_out.32.contigs 1294
Salt_Pond_MetaG_R1_C_H2O_MG_DASTool_bins_concoct_out.79.contigs 1132

In [9]:
model.medium = {'EX_cpd00067_e0': 1000.0,
 'EX_cpd00058_e0': 1000.0,
 'EX_cpd00013_e0': 1000.0,
 'EX_cpd00244_e0': 1000.0,
 'EX_cpd00205_e0': 1000.0,
 'EX_cpd00034_e0': 1000.0,
 'EX_cpd11574_e0': 1000.0,
 'EX_cpd00971_e0': 1000.0,
 'EX_cpd00048_e0': 1000.0,
 'EX_cpd00030_e0': 1000.0,
 'EX_cpd00305_e0': 100.0,
 'EX_cpd00001_e0': 1000.0,
 'EX_cpd10516_e0': 1000.0,
 'EX_cpd00007_e0': 1000.0,
 'EX_cpd00159_e0': 10.0,
 'EX_cpd25960_e0': 1000.0,
 'EX_cpd00063_e0': 1000.0,
 'EX_cpd00149_e0': 1000.0,
 'EX_cpd00254_e0': 1000.0,
 'EX_cpd00099_e0': 1000.0}

In [10]:
model.summary()

In [20]:
for k, v in model.medium.items():
    rxn_ex = model.reactions.get_by_id(k)
    print(rxn_ex, rxn_ex.build_reaction_string(True), v)

EX_cpd00067_e0: cpd00067_e0 <=>  H+ [e0] <=>  1000.0
EX_cpd00001_e0: cpd00001_e0 <=>  H2O [e0] <=>  1000.0
EX_cpd00058_e0: cpd00058_e0 <=>  Cu2+ [e0] <=>  1000.0
EX_cpd00013_e0: cpd00013_e0 <=>  NH3 [e0] <=>  1000.0
EX_cpd00244_e0: cpd00244_e0 <=>  Ni2+ [e0] <=>  1000.0
EX_cpd00205_e0: cpd00205_e0 <=>  K+ [e0] <=>  1000.0
EX_cpd00034_e0: cpd00034_e0 <=>  Zn2+ [e0] <=>  1000.0
EX_cpd11574_e0: cpd11574_e0 <=>  Molybdate [e0] <=>  1000.0
EX_cpd00971_e0: cpd00971_e0 <=>  Na+ [e0] <=>  1000.0
EX_cpd00048_e0: cpd00048_e0 <=>  Sulfate [e0] <=>  1000.0
EX_cpd00030_e0: cpd00030_e0 <=>  Mn2+ [e0] <=>  1000.0
EX_cpd00099_e0: cpd00099_e0 <=>  Cl- [e0] <=>  1000.0
EX_cpd10516_e0: cpd10516_e0 <=>  fe3 [e0] <=>  1000.0
EX_cpd00007_e0: cpd00007_e0 <=>  O2 [e0] <=>  1000.0
EX_cpd00159_e0: cpd00159_e0 <=>  L-Lactate [e0] <=>  10.0
EX_cpd25960_e0: cpd25960_e0 <=>  MePn [e0] <=>  1000.0
EX_cpd00063_e0: cpd00063_e0 <=>  Ca2+ [e0] <=>  1000.0
EX_cpd00305_e0: cpd00305_e0 <=>  Thiamin [e0] <=>  100.0
EX_cpd00149_e0: cpd00149_e0 <=>  Co2+ [e0] <=>  1000.0
EX_cpd00254_e0: cpd00254_e0 <=>  Mg [e0] <=>  1000.0

In [30]:
medium_no_phosphate_source = {
    'EX_cpd00067_e0': 1000.0,
 'EX_cpd00001_e0': 1000.0,
 'EX_cpd00058_e0': 1000.0,
 'EX_cpd00013_e0': 1000.0,
 'EX_cpd00244_e0': 1000.0,
 'EX_cpd00205_e0': 1000.0,
 'EX_cpd00034_e0': 1000.0,
 'EX_cpd11574_e0': 1000.0,
 'EX_cpd00971_e0': 1000.0,
 'EX_cpd00048_e0': 1000.0,
 'EX_cpd00030_e0': 1000.0,
 'EX_cpd00099_e0': 1000.0,
 'EX_cpd10516_e0': 1000.0,
 'EX_cpd00007_e0': 1000.0,
'EX_cpd10515_e0': 1000.0,
 'EX_cpd00159_e0': 10.0,
 'EX_cpd25960_e0': 0.0, #m
 'EX_cpd00063_e0': 1000.0,
 'EX_cpd00305_e0': 100.0,
 'EX_cpd00149_e0': 1000.0,
 'EX_cpd00254_e0': 1000.0}
medium_pi = {
    'EX_cpd00067_e0': 1000.0,
 'EX_cpd00001_e0': 1000.0,
 'EX_cpd00058_e0': 1000.0,
 'EX_cpd00013_e0': 1000.0,
 'EX_cpd00244_e0': 1000.0,
 'EX_cpd00205_e0': 1000.0,
 'EX_cpd00034_e0': 1000.0,
 'EX_cpd11574_e0': 1000.0,
 'EX_cpd00971_e0': 1000.0,
 'EX_cpd00048_e0': 1000.0,
 'EX_cpd00030_e0': 1000.0,
 'EX_cpd00099_e0': 1000.0,
 'EX_cpd10516_e0': 1000.0,
    'EX_cpd10515_e0': 1000.0,
 'EX_cpd00007_e0': 1000.0,
 'EX_cpd00159_e0': 10.0,
 'EX_cpd00009_e0': 1000, 
 'EX_cpd00063_e0': 1000.0,
 'EX_cpd00305_e0': 100.0,
 'EX_cpd00149_e0': 1000.0,
 'EX_cpd00254_e0': 1000.0}
medium_mepn = {
    'EX_cpd00067_e0': 1000.0,
 'EX_cpd00001_e0': 1000.0,
 'EX_cpd00058_e0': 1000.0,
 'EX_cpd00013_e0': 1000.0,
 'EX_cpd00244_e0': 1000.0,
 'EX_cpd00205_e0': 1000.0,
 'EX_cpd00034_e0': 1000.0,
 'EX_cpd11574_e0': 1000.0,
 'EX_cpd00971_e0': 1000.0,
 'EX_cpd00048_e0': 1000.0,
 'EX_cpd00030_e0': 1000.0,
 'EX_cpd00099_e0': 1000.0,
 'EX_cpd10516_e0': 1000.0,
    'EX_cpd10515_e0': 1000.0,
 'EX_cpd00007_e0': 1000.0,
 'EX_cpd00159_e0': 10.0,
 'EX_cpd00009_e0': 1000, 
 'EX_cpd25960_e0': 1000, 
 'EX_cpd00063_e0': 1000.0,
 'EX_cpd00305_e0': 100.0,
 'EX_cpd00149_e0': 1000.0,
 'EX_cpd00254_e0': 1000.0}
medium_both = {
    'EX_cpd00067_e0': 1000.0,
 'EX_cpd00001_e0': 1000.0,
 'EX_cpd00058_e0': 1000.0,
 'EX_cpd00013_e0': 1000.0,
 'EX_cpd00244_e0': 1000.0,
 'EX_cpd00205_e0': 1000.0,
 'EX_cpd00034_e0': 1000.0,
 'EX_cpd11574_e0': 1000.0,
 'EX_cpd00971_e0': 1000.0,
 'EX_cpd00048_e0': 1000.0,
 'EX_cpd00030_e0': 1000.0,
 'EX_cpd00099_e0': 1000.0,
 'EX_cpd10516_e0': 1000.0,
 'EX_cpd00007_e0': 1000.0,
 'EX_cpd00159_e0': 10.0,
 'EX_cpd25960_e0': 1000, 
 'EX_cpd00063_e0': 1000.0,
 'EX_cpd00305_e0': 100.0,
 'EX_cpd00149_e0': 1000.0,
 'EX_cpd00254_e0': 1000.0}
test = {
    'null': medium_no_phosphate_source,
    'mepn': medium_mepn,
    'pi': medium_no_phosphate_source,
    'both': medium_both,
}
for model_id, model in models.items():
    test_res = {}
    for label, medium in test.items():
        model.medium = medium
        model.objective = 'bio1'
        obj_val = model.slim_optimize()
        test_res[label] = obj_val
    print(model_id, test_res)

KeyError: 'EX_cpd10515_e0'

In [ ]:
model.medium

In [19]:
model = models['Salt_Pond_MetaG_R2_C_D1_MG_DASTool_bins_concoct_out.88.contigs']

In [15]:
model.medium = medium_both

In [16]:
model.summary()

In [20]:
model.summary()